A1B4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('wow/', include('wow.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

wow/urls.py
from django.urls import path

from . import views

app_name = 'wow'

urlpatterns = [
    path('', views.index, name='index'),
    path('input_info/', views.input_info, name='input_info'),
    path('input_info/creating', views.creating, name='creating'), # stt 해주는 부분
    path('input_info/sum', views.sum, name='sum'), # lexrank 결과
    path('summary_result/', views.summary_result, name='summary_result'), # 요약 나오는 부분(지금은 안 쓰지만 일단 냅둠)
    path('report_result/', views.show_report, name='report_result'), # report page
    path('report/', views.report, name='report'), # 최종 보고서 부분
    path("notion_share/", views.notion_share, name="notion_share"), # notion
    path('report_result/calendar_goo/', views.calendar_share, name="calendar_share")
]

wow/models.py
from django.db import models
import datetime


class Input(models.Model):
    objects = models.Manager()
    
    title = models.CharField(max_length=50)
    date = models.DateField(default=datetime.date.today)
    members = models.CharField(max_length=60)
    tag = models.CharField(max_length=10)
    wav = models.FileField(upload_to="")

wow/forms.py
from django import forms
from .models import Input

class InputForm(forms.ModelForm):
    class Meta:
        model = Input
        fields = ['title', 'date', 'members', 'tag', 'wav']

wow/templates/wow/index.html
<!DOCTYPE html>
<html>
{% load static %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, target-densitydpi=medium-dpi" />
  <title>WoW</title>
  <link rel="stylesheet" type="text/css" href="{% static 'wow/style.css' %}">
  <link rel="stylesheet" type="text/javascript" href="{% static 'wow/scripts.js' %}">
  <style id="applicationStylesheet" type="text/css">
	
	.image {
		background-image: url("{% static 'wow/images/bg.png' %}");
		background-size: cover;
	  }

	a { text-decoration:none ; color:#000000}
	.mediaViewInfo {
		--web-view-name: A1B4;
		--web-view-id: _1920__1;
		--web-scale-on-resize: true;
		--web-enable-deep-linking: true;
	}
	:root {
		--web-view-ids: _1920__1;
	}
	* {
		margin: 0;
		padding: 0;
		box-sizing: border-box;
		border: none;
	}
	#_1920__1 {
		position: absolute;
		width: 100%;
		height: 100%;
		background-color: rgba(255,255,255,1);
		overflow: hidden;
		--web-view-name: 웹 1920 – 1;
		--web-view-id: _1920__1;
		--web-scale-on-resize: true;
		--web-enable-deep-linking: true;
	}
	#bg {
		opacity: 0.953;
		position: absolute;
		width: 100%;
		height: 100%;
		left: 0px;
		top: 0px;
		overflow: visible;
	}
	#__elli19__httpsunsplashcom {
		left: 120px;
		top: 880px;
		position: absolute;
		overflow: visible;
		width: 105px;
		white-space: nowrap;
		line-height: 15px;
		margin-top: -1.5px;
		text-align: left;
		font-family: NanumSquare;
		font-style: normal;
		font-weight: normal;
		font-size: 12px;
		color: rgba(100,100,100,1);
	}
	#Banner_Text {
		position: absolute;
		width: 501px;
		height: 302px;
		left: 749px;
		top: 289px;
		overflow: visible;
	}
	#Creating__Remote_meeting__Repo {
		left: 0px;
		top: 98px;
		position: absolute;
		overflow: visible;
		width: 502px;
		white-space: nowrap;
		line-height: 64px;
		margin-top: -0.5px;
		text-align: left;
		font-family: AppleSDGothicNeoH00;
		font-style: normal;
		font-weight: normal;
		font-size: 63px;
		color: rgba(255,255,255,1);
	}
	#About_us {
		left: 200px;
		top: 0px;
		position: absolute;
		overflow: visible;
		width: 88px;
		white-space: nowrap;
		line-height: 30px;
		margin-top: -3px;
		text-align: left;
		font-family: NanumSquare;
		font-style: normal;
		font-weight: normal;
		font-size: 24px;
		color: rgba(255,255,255,1);
	}
	#_2 {
		position: absolute;
		width: 136px;
		height: 64px;
		left: 128px;
		top: 63px;
		overflow: visible;
	}
	#A1B4 {
		left: 79px;
		top: 18px;
		position: absolute;
		overflow: visible;
		width: 58px;
		white-space: nowrap;
		line-height: 28px;
		margin-top: -2px;
		text-align: left;
		font-family: NanumSquare;
		font-style: normal;
		font-weight: normal;
		font-size: 24px;
		color: rgba(84,84,84,1);
		letter-spacing: 1px;
	}
	#_104 {
		fill: rgba(235,235,235,1);
	}
	._104 {
		overflow: visible;
		position: absolute;
		width: 64px;
		height: 64px;
		left: 0px;
		top: 0px;
		transform: matrix(1,0,0,1,0,0);
	}
	#report {
		position: absolute;
		width: 24.75px;
		height: 31.5px;
		left: 20px;
		top: 15px;
		overflow: visible;
	}
	#_105 {
		fill: rgba(0,0,0,1);
	}
	._105 {
		overflow: visible;
		position: absolute;
		width: 9px;
		height: 2.25px;
		left: 5.625px;
		top: 18px;
		transform: matrix(1,0,0,1,0,0);
	}
	#_106 {
		fill: rgba(0,0,0,1);
	}
	._106 {
		overflow: visible;
		position: absolute;
		width: 13.5px;
		height: 2.25px;
		left: 5.625px;
		top: 12.375px;
		transform: matrix(1,0,0,1,0,0);
	}
	#_107 {
		fill: rgba(0,0,0,1);
	}
	._107 {
		overflow: visible;
		position: absolute;
		width: 5.625px;
		height: 2.25px;
		left: 5.625px;
		top: 23.625px;
		transform: matrix(1,0,0,1,0,0);
	}
	#_108 {
		fill: rgba(0,0,0,1);
	}
	._108 {
		overflow: visible;
		position: absolute;
		width: 24.75px;
		height: 31.5px;
		left: 0px;
		top: 0px;
		transform: matrix(1,0,0,1,0,0);
	}
	#Button_Schedule_Visit__1 {
		position: absolute;
		width: 256px;
		height: 56px;
		left: 872px;
		top: 695px;
		overflow: visible;
	}
	#_4 {
		fill: rgba(255,255,255,1);
	}
	._4 {
		position: absolute;
		overflow: visible;
		width: 256px;
		height: 56px;
		left: 0px;
		top: 0px;
	}
	#Start {
		left: 103px;
		top: 14px;
		position: absolute;
		overflow: visible;
		width: 51px;
		white-space: nowrap;
		line-height: 32px;
		margin-top: -4px;
		text-align: center;
		font-family: AppleSDGothicNeoSB00;
		font-style: normal;
		font-weight: normal;
		font-size: 24px;
		color: rgba(84,88,113,1);
	}
</style>
<script id="applicationScript">

</script>
</head>
<body>
<div id="_1920__1" style="width: 100%;max-height: 100%">
	<img id="bg" src="{% static 'wow/images/bg.png' %}">
	<div id="__elli19__httpsunsplashcom">
		<span>이미지 |<br/>@visuals, https://unsplash.com/</span>
	</div>
	<div id="Banner_Text" class="Banner_Text">
		<div id="Creating__Remote_meeting__Repo">
			<span>Creating <br/>Remote meeting <br/>Report</span>
		</div>
		<div id="About_us">
			<a href="https://github.com/oleeyoung520/free_project" target="_blank" style="color:#d8d8d8">About us</a>
			<!-- <span href='https://ojji.wayful.com'>About us</span> -->
		</div>
	</div>
	<div id="_2">
		<div id="A1B4">
			<span>A1B4</span>
		</div>
		<svg class="_104" viewBox="0 0 64 64">
			<path id="_104" d="M 32 0 C 49.67311096191406 0 64 14.32688903808594 64 32 C 64 49.67311096191406 49.67311096191406 64 32 64 C 14.32688903808594 64 0 49.67311096191406 0 32 C 0 14.32688903808594 14.32688903808594 0 32 0 Z">
			</path>
		</svg>
		<div id="report">
			<svg class="_105" viewBox="11.25 20.25 9 2.25">
				<path id="_105" d="M 11.25 20.25 L 20.25 20.25 L 20.25 22.5 L 11.25 22.5 L 11.25 20.25 Z">
				</path>
			</svg>
			<svg class="_106" viewBox="11.25 14.625 13.5 2.25">
				<path id="_106" d="M 11.25 14.625 L 24.75 14.625 L 24.75 16.875 L 11.25 16.875 L 11.25 14.625 Z">
				</path>
			</svg>
			<svg class="_107" viewBox="11.25 25.875 5.625 2.25">
				<path id="_107" d="M 11.25 25.875 L 16.875 25.875 L 16.875 28.125 L 11.25 28.125 L 11.25 25.875 Z">
				</path>
			</svg>
			<svg class="_108" viewBox="5.625 2.25 24.75 31.5">
				<path id="_108" d="M 28.125 5.625 L 24.75 5.625 L 24.75 4.5 C 24.75 3.257359266281128 23.74264144897461 2.25 22.5 2.25 L 13.5 2.25 C 12.25735950469971 2.25 11.25 3.257359504699707 11.25 4.500000476837158 L 11.25 5.625 L 7.875 5.625 C 6.632359504699707 5.625 5.625 6.632359504699707 5.625 7.875000476837158 L 5.625 31.5 C 5.625 32.74264144897461 6.632359504699707 33.75 7.875 33.75 L 28.125 33.75 C 29.36764144897461 33.75 30.375 32.74264144897461 30.375 31.5 L 30.375 7.875 C 30.375 6.632359504699707 29.36764144897461 5.625 28.125 5.625 Z M 13.5 4.5 L 22.5 4.5 L 22.5 9 L 13.5 9 L 13.5 4.5 Z M 28.125 31.5 L 7.875 31.5 L 7.875 7.875 L 11.25 7.875 L 11.25 11.25 L 24.75 11.25 L 24.75 7.875 L 28.125 7.875 L 28.125 31.5 Z">
				</path>
			</svg>
		</div>
	</div>
	<div class="jumbotron text-center">
	<div id="Button_Schedule_Visit__1" class="Button_Schedule_Visit___1">
		<svg xmlns="http://www.w3.org/2000/svg" width="256" height="56" viewBox="0 0 256 56">
			<a
			xlink:href="{% url 'wow:input_info' %}">
			<rect width="256" height="56" fill="#fff" rx="28"/>
			<text fill="#545871" font-family="AppleSDGothicNeoSB00" font-size="24px" transform="translate(128 36)">
				<tspan x="-24.696" y="0">Start</tspan>
			</text>
			</a>
		</svg>
	</div>
</div>
</body>
</html>